# Displays name
name: Docker Lynis Security Scan 

on:
  push:
    branches: [ main ] # will run automatically when pushed to main
  workflow_dispatch:   # # Adds a "run workflow" button so it can be triggered manually

jobs: # Job is called lynis-scan
  lynis_scan:
    runs-on: ubuntu-latest # gives you a ubuntu vm to do the work

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Pulls your repository files into the runner so subsequent steps can access them

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Preps a modern Docker build environment (multi-platform capable, better caching). It’s the standard way to build images in Actions now

      - name: Build Lynis image
        run: docker build -t lynis-sec ./docker-lynis # docker build: compiles your image using the Dockerfile in ./Docker-lynis, -t lynis-sec: tags the image so we can reference it by name later

      - name: Prepare log directory
        run: mkdir -p logs # Creates a logs/ folder at the repo root on the runner. We’ll mount this into the container so the scan output lands in a place the runner can read.

      - name: Run Lynis container (write log to mounted folder)
        run: docker run --rm -v "${{ github.workspace }}/logs:/var/log/lynis-scan" lynis-sec
        # docker run: starts the container based on the image we build
        # --rm: cleans it up after exits
        # -v "${{ github.workspace }}/logs:/var/log/lynis-scan": mounts the runner’s logs/ into the container at /var/log/lynis-scan
        # The lynis-scan.sh writes to /var/log/lynis-scan/scan.log inside the container.

      - name: Show last lines in summary
        run: |
          echo "### Lynis scan tail" >> $GITHUB_STEP_SUMMARY
          tail -n 50 logs/scan.log >> $GITHUB_STEP_SUMMARY
        # Appends the last ~50 lines of the log into the run’s Summary tab so you can preview results without downloading the artifact
      - name: Upload scan log artifact
        uses: actions/upload-artifact@v4
        with:
          name: lynis-scan-log
          path: logs/scan.log
          if-no-files-found: error
        # Publishes logs/scan.log as a downloadable artifact attached to the workflow run
