name: Docker Lynis Security Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: docker-lynis-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lynis_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug workspace (quick tree)
        run: |
          pwd
          echo "=== top level ==="
          ls -la
          echo "=== find Dockerfile (depth 4) ==="
          find . -maxdepth 4 -iname "Dockerfile" -print || true

      # 🔒 Safeguard: verify expected folder + Dockerfile exist
      - name: Verify docker-lynis folder and Dockerfile exist
        run: |
          if [ ! -d "./docker-lynis" ]; then
            echo "ERROR: ./docker-lynis folder not found in repo root."
            exit 1
          fi
          if [ ! -f "./docker-lynis/Dockerfile" ]; then
            echo "ERROR: ./docker-lynis/Dockerfile not found."
            echo "Make sure your Dockerfile is at: repo-root/docker-lynis/Dockerfile"
            exit 1
          fi
          echo "docker-lynis folder and Dockerfile found ✅"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Lynis image
        run: docker build -t lynis-sec ./docker-lynis

      - name: Prepare log directory
        run: mkdir -p logs

      - name: Run Lynis container (writes log to mounted folder)
        run: docker run --rm -v "${{ github.workspace }}/logs:/var/log/lynis-scan" lynis-sec

      # 🔒 Safeguard: ensure log exists and isn’t empty
      - name: Verify log created and non-empty
        run: |
          if [ ! -s logs/scan.log ]; then
            echo "ERROR: logs/scan.log missing or empty."
            echo "Tips:"
            echo " - Ensure lynis-scan.sh runs: cd /opt/lynis && ./lynis audit system | tee /var/log/lynis-scan/scan.log"
            echo " - Ensure lynis-scan.sh is copied next to Dockerfile and chmod +x in the image."
            echo " - Ensure the run step mounts logs correctly."
            exit 1
          fi
          echo "scan.log present and non-empty ✅"

      - name: Show last lines in summary
        run: |
          echo "### Lynis scan tail" >> $GITHUB_STEP_SUMMARY
          tail -n 50 logs/scan.log >> $GITHUB_STEP_SUMMARY

      - name: Upload scan log artifact
        uses: actions/upload-artifact@v4
        with:
          name: lynis-scan-log
          path: logs/scan.log
          if-no-files-found: error







