name: Docker Lynis Security Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lynis_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Lynis image
        run: docker build -t lynis-sec ./docker/lynis

      - name: Prepare log directory
        run: mkdir -p logs

      - name: Run Lynis container (write log to mounted folder)
        run: docker run --rm -v "${{ github.workspace }}/logs:/var/log/lynis-scan" lynis-sec

      - name: Show last lines in summary
        run: |
          echo "### Lynis scan tail" >> $GITHUB_STEP_SUMMARY
          tail -n 50 logs/scan.log >> $GITHUB_STEP_SUMMARY

      - name: Upload scan log artifact
        uses: actions/upload-artifact@v4
        with:
          name: lynis-scan-log
          path: logs/scan.log
          if-no-files-found: error






